---
kind: pipeline
type: ssh
name: deploy

server:
    host:
        from_secret: host
    user:
        from_secret: username
    ssh_key:
        from_secret: ssh_key

clone:
    disable: true

trigger:
    branch:
        - master

steps:
    - name: hello
      commands:
          - sudo -Hu www-data git -C /var/www/benharr.is pull --rebase origin master

