---
kind: pipeline
type: ssh
name: deploy

server:
    host:
        from_secret: host
    user:
        from_secret: username
    ssh_key:
        from_secret: ssh_key

steps:
    - name: hello
      commands:
          - cd /var/www/benharr.is
          - sudo -Hu www-data git pull origin master

