---
kind: pipeline
type: ssh
name: deploy

server:
    host:
        from_secret: host
    user:
        from_secret: username
    ssh_key:
        from_secret: ssh_key

steps:
    - name: hello
      commands:
          - echo hello world
          - head -n5 /home/ben/insults.txt

